package com.pwc.sns.util;

public interface SNSConstants {
	
	String OAUTH_TOKEN_SEC = "OAUTH_TOKEN_SEC";
	
	String OAUTH_TOKEN = "OAUTH_TOKEN";
	
	String TWITTER_REQUESTTOKEN_URL = "TWITTER_REQUESTTOKEN_URL";
	
	String TWITTER_CALLBACK = "TWITTER_CALLBACK";
	
	String TWITTER_KEY = "TWITTER_KEY";
	
	String TWITTER_SEC = "TWITTER_SEC";
	
	String TWITTER_AUTHTOKEN_URL = "TWITTER_AUTHTOKEN_URL";
	
	String LINKEDIN_AUTHTOKEN_URL = "LINKEDIN_AUTHTOKEN_URL";
	
	String LINKEDIN_CALLBACK = "LINKEDIN_CALLBACK";
	
	String LINKEDIN_KEY = "LINKEDIN_KEY";
	
	String FACEBOOK_AUTHTOKEN_URL = "FACEBOOK_AUTHTOKEN_URL";
	
	String FACEBOOK_CALLBACK = "FACEBOOK_CALLBACK";
	
	String FACEBOOK_CLIENTID = "FACEBOOK_CLIENTID";
	
	String GOOGLE_CLIENTID = "GOOGLE_CLIENTID";
	
	String GOOGLE_CALLBACK = "GOOGLE_CALLBACK";
	
	String GOOGLE_SEC = "GOOGLE_SEC";
	
	String LINKEDIN_REFRESHTOKEN_REQUEST = "LINKEDIN_REFRESHTOKEN_REQUEST";
	
	String LINKEDIN_REFRESHTOKEN_OAUTH = "LINKEDIN_REFRESHTOKEN_OAUTH";
	
	String CLIENT_LANDING_SERVLET = "ClientLandingServlet";
}
